server:
  port: 8084

spring:
  application:
    name: song-service
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
  datasource:
    url: jdbc:postgresql://song-db:5432/song-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
