server:
  port: 8084

spring:
  application:
    name: song-service
  jpa:
    show-sql: true
    hibernate:
      format_sql: true
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5433/song-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
