server:
  port: 8083

spring:
  application:
    name: resource-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://resource-db:5432/resource-db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

song-service:
  url: http://song-service:8084
